const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('mayhem', {
  getAugments: () => ipcRenderer.invoke('data:augments'),
  getChampions: () => ipcRenderer.invoke('data:champions'),
  getItems: () => ipcRenderer.invoke('data:items'),
  getAugmentStats: () => ipcRenderer.invoke('data:augment-stats'),
  getChampionStats: () => ipcRenderer.invoke('data:champion-stats'),
  refreshData: () => ipcRenderer.invoke('data:refresh'),
  onDataStatus: (cb) => ipcRenderer.on('data:status', (_e, s) => cb(s)),
  onDataRefreshed: (cb) => ipcRenderer.on('data:refreshed', () => cb()),
  onPrepSession: (cb) => ipcRenderer.on('prep:session', (_e, s) => cb(s)),
  onPrepChampData: (cb) => ipcRenderer.on('prep:champdata', (_e, d) => cb(d)),
  getHistory: () => ipcRenderer.invoke('history:get'),
  ingestHistory: () => ipcRenderer.invoke('history:ingest'),
  getBuilds: () => ipcRenderer.invoke('builds:get'),
  saveBuild: (build) => ipcRenderer.invoke('builds:save', build),
  deleteBuild: (id) => ipcRenderer.invoke('builds:delete', id),
  getRatings: () => ipcRenderer.invoke('ratings:get'),
  setRating: (name, score) => ipcRenderer.invoke('ratings:set', { name, score }),
  scanScreen: () => ipcRenderer.invoke('ocr:scan'),
  notifyPicked: () => ipcRenderer.send('ocr:picked'),
  showBadges: (badges) => ipcRenderer.send('badges:show', badges),
  clearBadges: () => ipcRenderer.send('badges:clear'),
  onBadges: (cb) => ipcRenderer.on('badges:data', (_e, b) => cb(b)),
  onBadgesClear: (cb) => ipcRenderer.on('badges:clear', () => cb()),
  showBuildStrip: (data) => ipcRenderer.send('buildstrip:show', data),
  clearBuildStrip: () => ipcRenderer.send('buildstrip:clear'),
  onBuildStrip: (cb) => ipcRenderer.on('buildstrip:data', (_e, d) => cb(d)),
  onBuildStripClear: (cb) => ipcRenderer.on('buildstrip:clear', () => cb()),
  stripResize: (w, h) => ipcRenderer.send('strip:resize', { w, h }),
  stripLock: (v) => ipcRenderer.send('strip:lock', v),
  stripDragBy: (dx, dy) => ipcRenderer.send('strip:dragby', { dx, dy }),
  stripDragEnd: () => ipcRenderer.send('strip:dragend'),
  onCsPills: (cb) => ipcRenderer.on('cs:data', (_e, d) => cb(d)),
  onCsClear: (cb) => ipcRenderer.on('cs:clear', () => cb()),
  showPrio: (data) => ipcRenderer.send('prio:show', data),
  onPrio: (cb) => ipcRenderer.on('prio:data', (_e, d) => cb(d)),
  scanClick: () => ipcRenderer.send('scanbtn:click'),
  onHotkeyStatus: (cb) => ipcRenderer.on('hotkeys:status', (_e, s) => cb(s)),
  onOcrOffer: (cb) => ipcRenderer.on('ocr:offer', (_e, r) => cb(r)),
  onOcrStatus: (cb) => ipcRenderer.on('ocr:status', (_e, s) => cb(s)),
  onAutoPicked: (cb) => ipcRenderer.on('ocr:auto-picked', (_e, d) => cb(d)),
  setClickThrough: (v) => ipcRenderer.send('overlay:set-clickthrough', v),
  hide: () => ipcRenderer.send('overlay:hide'),
  setCollapsed: (v) => ipcRenderer.send('overlay:collapse', v),
  onLiveUpdate: (cb) => ipcRenderer.on('live:update', (_e, s) => cb(s)),
  onLiveEnded: (cb) => ipcRenderer.on('live:ended', () => cb()),
  onAugmentBreakpoint: (cb) => ipcRenderer.on('live:augment-breakpoint', (_e, d) => cb(d)),
  onPhase: (cb) => ipcRenderer.on('lcu:phase', (_e, d) => cb(d)),
  onHistoryUpdated: (cb) => ipcRenderer.on('history:updated', (_e, g) => cb(g)),
  onBuildsUpdated: (cb) => ipcRenderer.on('builds:updated', (_e, b) => cb(b)),
  onChampData: (cb) => ipcRenderer.on('aramgg:champdata', (_e, d) => cb(d)),
  onClickThrough: (cb) => ipcRenderer.on('overlay:clickthrough', (_e, v) => cb(v)),
});
